CREATE TABLE IF NOT EXISTS Genres (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	genre_name varchar(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	artist_name varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist_genres (
	genre_id integer REFERENCES Genres (id),
	artist_id integer REFERENCES Artists (id),
	CONSTRAINT pk_artist_genres PRIMARY KEY (genre_id, artist_id)
);

CREATE TABLE IF NOT EXISTS Albums (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	album_name varchar(255) NOT NULL,
	album_year integer NOT NULL
		CHECK (album_year BETWEEN 0 AND 9999)
	);

CREATE TABLE IF NOT EXISTS Album_of_artist (
	artist_id integer REFERENCES Artists (id),
	album_id integer REFERENCES Albums (id),
	CONSTRAINT pk_album_of_artist PRIMARY KEY (album_id, artist_id)
);

CREATE TABLE IF NOT EXISTS Tracks (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	track_name varchar(255) NOT NULL,
	track_length time NOT NULL,
	album_id integer REFERENCES Albums (id)
);

CREATE TABLE IF NOT EXISTS Collections (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	collection_name varchar(255) NOT NULL,
	collection_year integer NOT NULL
		CHECK (collection_year BETWEEN 0 AND 9999)
);

CREATE TABLE IF NOT EXISTS Collection (
	track_id integer REFERENCES Tracks (id),
	collection_id integer REFERENCES Collections (id),
	CONSTRAINT pk_collection PRIMARY KEY (track_id, collection_id)
);