CREATE TABLE IF NOT EXISTS genres (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	genre_name varchar(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS artists (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	artist_name varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS artist_genres (
	genre_id integer REFERENCES genres (id),
	artist_id integer REFERENCES artists (id),
	CONSTRAINT pk_artist_genres PRIMARY KEY (genre_id, artist_id)
);

CREATE TABLE IF NOT EXISTS albums (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	album_name varchar(255) NOT NULL,
	album_year integer NOT NULL
		CHECK (album_year BETWEEN 0 AND 9999)
	);

CREATE TABLE IF NOT EXISTS album_of_artist (
	artist_id integer REFERENCES artists (id),
	album_id integer REFERENCES albums (id),
	CONSTRAINT pk_album_of_artist PRIMARY KEY (album_id, artist_id)
);

CREATE TABLE IF NOT EXISTS tracks (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	track_name varchar(255) NOT NULL,
	track_length time NOT NULL,
	album_id integer REFERENCES albums (id)
);

CREATE TABLE IF NOT EXISTS collections (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	collection_name varchar(255) NOT NULL,
	collection_year integer NOT NULL
		CHECK (collection_year BETWEEN 0 AND 9999)
);

CREATE TABLE IF NOT EXISTS collection (
	track_id integer REFERENCES tracks (id),
	collection_id integer REFERENCES collections (id),
	CONSTRAINT pk_collection PRIMARY KEY (track_id, collection_id)
);